### ISSUE TITLE
error in home.dart in void initstate

### ISSUE THREAD

**Issue by dragonemperor03** [ufrshubham/That-Wallpaper-App#1]
^
lib/home.dart:27:35: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
      var category = document.data("tag");
                                  ^
lib/home.dart:31:41: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        categoryImages.add(document.data("url"));

here's the code ive followed from your tutorial running flutter 1.22.4 using android studio
  
  @override
  void initState(){
    super.initState();

    widget.snapshot.data.docs.forEach((document) {
      var category = document.data('tag');

      if (!categories.contains(category)) {
        categories.add('category');
        categoryImages.add(document.data('url'));
      }
    });
  }

**Comment by ufrshubham** [comment]
I think it might be because of breaking changes in latest cloud_firestore package. Can you paste the list of packages along with their version number from your pubspec.yml?

**Comment by dragonemperor03** [comment]
Thanks for the response! But I’ve fixed it now!
Solution was
.data()[‘tag’];

**Comment by ufrshubham** [comment]
> Thanks for the response! But I’ve fixed it now!
> Solution was
> .data()[‘tag’];

Yep, that's definitely because of latest version of cloud_firestore. Good to know that you solved it!
